### ISSUE TITLE
Add eslint-plugin-ava

### ISSUE THREAD

**Issue by nunof07** [EvgenyOrekhov/eslint-config-hardcore#103]
Thanks for this config. It's really useful!

How about adding [eslint-plugin-ava](https://github.com/avajs/eslint-plugin-ava)? Is this something that makes sense to include in this config?

**Comment by EvgenyOrekhov** [comment]
You're welcome!

For now I want to keep eslint-config-hardcore framework-agnostic.

Personally, I use Jest, and there are `jest/all` and `jest-formatting/strict` configs which enable all available rules. So for Jest, it doesn't really make sense to include it here, since it's just 2 lines of code.

I can see there is [`ava/recommended`](https://github.com/avajs/eslint-plugin-ava#recommended-config). If it's not strict enough for you, perhaps you could ask its maintainers to create `ava/strict` config.

**Comment by nunof07** [comment]
I think it makes sense to keep this config framework-agnostic.

I'll install it separately and use `ava/recommended`.

Thank you!
