### ISSUE TITLE
Configuration for rule "unicorn/prevent-abbreviations" is invalid

### ISSUE THREAD

**Issue by Arslanoov** [EvgenyOrekhov/eslint-config-hardcore#318]
Hello
After installing the plugin this error occurs
"Configuration for rule "unicorn/prevent-abbreviations" is invalid"
.eslintrc
![2](https://user-images.githubusercontent.com/51407990/124960599-ebddc400-e035-11eb-8fae-fcf34493f540.png)
Error
![1](https://user-images.githubusercontent.com/51407990/124960623-ef714b00-e035-11eb-9a61-a6f68ce80880.png)

**Comment by EvgenyOrekhov** [comment]
Hello! I need more info about your environment.

1.Could you tell me which version of ESLint you have in `package.json`?
2. I can see from your log that the error comes from PHPStorm's integrated ESLint plugin. Can you somehow check which version of ESLint does it use?
3. Do you have the same error when you run the local version of ESLint? You can try that by running `npx eslint .` in the project root folder.

**Comment by Arslanoov** [comment]
Thank you for the response
1. 7.24.0
My deps:
![1](https://user-images.githubusercontent.com/51407990/125037586-c68c9c80-e0ad-11eb-8a1a-d6eef9d220a0.png)
2. It uses eslint from node_modules package
![2](https://user-images.githubusercontent.com/51407990/125037607-cb515080-e0ad-11eb-85a7-1397d183a022.png)
3. Yes, same error :(
![3](https://user-images.githubusercontent.com/51407990/125037627-d0ae9b00-e0ad-11eb-8fb5-d5441d47c705.png)

**Comment by EvgenyOrekhov** [comment]
Thanks! Could you also check which version of `eslint-plugin-unicorn` you have in your `package-lock.json`?

**Comment by Arslanoov** [comment]
34.0.1
![1](https://user-images.githubusercontent.com/51407990/125161990-f9628d80-e19e-11eb-902e-685f5ce9cadd.png)

**Comment by EvgenyOrekhov** [comment]
That looks right! Hmm, I'm puzzled... Would you be able to create a minimal reproducible case, preferably as a GitHub repo? I would really appreciate it!

**Comment by Arslanoov** [comment]
https://github.com/Arslanoov/nuxt-blog/tree/eslint-hardcode

**Comment by EvgenyOrekhov** [comment]
I see in your `package-lock.json` that `@nuxtjs/eslint-config` requires `"eslint-plugin-unicorn": "^28.0.2"` (line 4375). but `eslint-config-hardcore` requires `"eslint-plugin-unicorn": "^34.0.1"`. And you actually end up with two different versions of `eslint-plugin-unicorn` (line 13493 and line 14232), but version 28.0.2 takes precedence when you run ESLint.

So it's not a problem with eslint-config-hardcore.

I have a few suggestions for you:

1. File a bug report to https://github.com/nuxt/eslint-config and ask them to upgrade `eslint-plugin-unicorn`.
2. In the meantime, disable rules that cause errors. (I guess there might be quite a few of those because Nuxt.js's `eslint-plugin-unicorn` is really old)

**Comment by Arslanoov** [comment]
Oh, I get it. Thank you so much
