### ISSUE TITLE
@shopify/eslint-plugin has security warnings, how to deal with them?

### ISSUE THREAD

**Issue by martijnhartlief** [EvgenyOrekhov/eslint-config-hardcore#557]
We're trying to resolve some dependabot security warnings that come from eslint-config-hardcore, for example:
`@graphql-tools/url-loader@6.10.1` > `graphql-config` > `eslint-plugin-graphql` > `@shopify/eslint-plugin`

Since eslint-plugin-graphql is being deprecated and there hasn't been movement in @shopify/eslint-plugin to replace the package, is there any way around this?

- [ ] https://github.com/Shopify/web-configs/issues/327

**Comment by EvgenyOrekhov** [comment]
You probably don't need to worry about GraphQL-related packages since GraphQL-related rules are not included in **eslint-config-hardcore**.

BTW here's a good relevant article by Dan Abramov: [npm audit: Broken by Design](https://overreacted.io/npm-audit-broken-by-design/).

Also, I'm thinking about removing \@shopify/eslint-plugin since **eslint-config-hardcore** uses only a few rules from it, but \@shopify/eslint-plugin pulls too many transient dependencies.

**Comment by EvgenyOrekhov** [comment]
They fixed it in [@shopify/eslint-plugin@42.0.0](https://github.com/Shopify/web-configs/releases/tag/%40shopify%2Feslint-plugin%4042.0.0).
Released in [eslint-config-hardcore@24.8.1](https://github.com/EvgenyOrekhov/eslint-config-hardcore/releases/tag/v24.8.1).

![image](https://user-images.githubusercontent.com/8045060/176518664-76b96d1f-8cb2-4f0d-bafd-5cb9eb613dd4.png)
